### ISSUE TITLE
小獅子,小青蛙,小白鯨,長頸鹿的圖要縮小,放完整

### ISSUE THREAD

**Issue by as821012** [babyinbook/preview#14]

**Comment by ClaudiaLee** [comment]
＠Jane，由於這是我們從繪本中找出來的圖，裁切出來的大小。要繪小的完整圖，麻煩JANE請提供這四個角色的JPG檔，尺寸大小為210*210 PIX。

**Comment by jane1978** [comment]
动物小图可以从我云盘里插图的原图里截取

**Comment by kinsyou** [comment]
@ClaudiaLee Jane的意思是在裁切的时候可以适当选择大一点的范围，把角色放完整就可以了。由于我们这里没有UI，能否请你们稍作上述调整？

**Comment by ClaudiaLee** [comment]
＠Kinsyou 設計美編的部份是由CAROL團隊在處理。
＠Carol，麻煩請看一下是否可以協助呢？

**Comment by TCarol** [comment]
這部份中午提供圖檔給IT更換

**Comment by TCarol** [comment]
已提供更換!

**Comment by ClaudiaLee** [comment]
已換圖，請確認是否OK。

**Comment by jane1978** [comment]
好的，没问题

**Comment by jane1978** [comment]
大象的图裁切也请选择大一些的范围，把形象放完整

**Comment by ClaudiaLee** [comment]
＠CAROL，這個也要麻煩CAROL協助喔。如果圖上有任何需要SUPPORT的地方，也請在這裡提出來喔。謝謝！

**Comment by TCarol** [comment]
@ClaudiaLee  已提供更換請收mail，謝謝!

**Comment by kinsyou** [comment]
已替换
