### ISSUE TITLE
目前只有15本，還有二個顏色的小女孩以及三個顏色小男孩的全部繪本，目前沒有素材(請KEVIN在上海確認)

### ISSUE THREAD

**Issue by as821012** [babyinbook/preview#17]

**Comment by kinsyou** [comment]
@as821012 请确认最终替换文字的方案，是否还需要缩小版的JPG，还是原版的pdf就可以（包括PDF中是否需要“某某某”）。总之请明确上海需要提供什么素材。

**Comment by kinsyou** [comment]
关于素材的整理
* 每个人物形象包含：封面封底，扉页，过渡（开头），过渡（中间），过渡（结尾），20个小故事，一共25个pdf文档。
* 一共六个人物形象，所以会有150个pdf档。

当前给了1个人物形象的25个pdf档，后续的会陆续交付。

**Comment by jane1978** [comment]
在替换其他人物形象 之前，请明确当前设置的名字的空格位置是否合适？还需要调整吗？如果在替换人物形象之后再调整名字的空格大小，排版和校对的工作量将会翻5倍。

**Comment by ClaudiaLee** [comment]
1. ＠JANE：繪本每一頁有名字地方，空格請確認為四個中文字的大小。
2. 最终替换文字的方案：請提供每個單頁300dpi的JPG檔。不要有某某某。
3. 請問 ： 过渡（开头），过渡（中间），过渡（结尾）分別是指雲盤上的哪個檔案？
4. 請協助將所有素材，150個PDF檔，全提供為上面規格的JPG檔。

**Comment by kinsyou** [comment]
* 我们理解，除了PDF档以外，需要提供网站使用的高精度JPG档，网站使用JPG档替换文字，生成预览JPG和印刷PDF（封面封底，内页两个pdf档）对吗？
* 关于JPG档，当前是希望名字留四个中文字的空格，由于字号，间距不同导致宽度也不相同，所以你这里需要宽度能否明确的制定一下吗？
* 我们比较关心替换的效果，由于名字有长有短（包括英文），请问是否根据留的空格宽度，调整好名字字体大小，和间距以后替换的？还是用其他方法来保证名字不过长？这种方法对名字字符数有什么限制？

**Comment by ClaudiaLee** [comment]
HI 各位，
先回覆如下。

Carol美女，
可否幫忙回覆空格的大小和間距？感謝！

Claudia Lee 李錦芬
方雲資訊雲端服務
Mobile： 0935558533
Tel：02-27405988
台北市大安區106忠孝東路四段221號8樓

**Comment by TCarol** [comment]
目前AI上使用的是方正喵鳴體18pt字級，字距 0 是沒壓到字的，以網頁pix來定空格寬度約300pix，平面為寬2.5cm

**Comment by jane1978** [comment]
现在正文的正常字号是15号，字间距为0，某某某的字号是20，字间距100.

**Comment by jane1978** [comment]
ClaudiaLee： 过渡（开头），过渡（中间），过渡（结尾）PDF文档在云盘—排版文件—女孩红色里有，分别标注为：开头、结尾、过渡

**Comment by kinsyou** [comment]
已经上传一个角色的所有高清Jpeg，顺序参见云盘上的说明档和pdf档。后续素材已经在安排制作。
