### ISSUE TITLE
生成的印刷用PDF的尺寸不对

### ISSUE THREAD

**Issue by kinsyou** [babyinbook/preview#24]
* 封面封底和内页是在两个不同的PDF档中，而且两者尺寸不同。
* 关于内页 样本是29.7x21.0，希望是29.1x21.6
* 精装的封面封底的尺寸是59.1x22.2
* 平装的封面封底尺寸也不同，不过考虑到时间有限，暂时考虑不提供平装选项。

**Comment by jane1978** [comment]
内页需要29.1*21.6的尺寸。

**Comment by kinsyou** [comment]
参见 https://github.com/babyinbook/preview/wiki/印刷相关标准

**Comment by kinsyou** [comment]
尺寸已经正确
