### ISSUE TITLE
预览书的顺序有问题

### ISSUE THREAD

**Issue by jane1978** [babyinbook/preview#26]
现在的前环衬1的位置不对，它应该是个单页，现在出现在双页的位置，后面则缺少了“冒险故事-女孩-红色-开头4”这一页。作为网站预览，是否可以把前环衬1的白页删除？然后在发给印厂的印刷文件里再加上这个前环衬1？
故事内文最后的一页白页也是多余的，但可以出现在预览中，但发给印厂的印刷文件里要删除。

**Comment by jane1978** [comment]
或者就是，作为预览的文件，把内文开头的白页和最后一页粉色页（这两个都是单页）都删除，但在制作印厂的印刷文件时都加上。也就是，用于预览的内文文件是40P，用于印刷的文件时42P。

**Comment by kinsyou** [comment]
参见 https://github.com/babyinbook/preview/wiki/印刷相关标准#图片顺序

**Comment by kinsyou** [comment]
封面文件也需要独立生成

**Comment by karaokok** [comment]
粉紅拿掉好像怪怪的，目前缺缺獨立生成 PDF

**Comment by kinsyou** [comment]
那就是最后再加粉红页和白页喽，效果可以，我已经修改了文档。PDF生成时需要注意最后是没有白页的。

**Comment by kinsyou** [comment]
顺序已确认，其他问题另外起issue
