### ISSUE TITLE
结算画面中的继续定制不起作用

### ISSUE THREAD

**Issue by kinsyou** [babyinbook/preview#28]
当前和去结算一样了。

**Comment by karaokok** [comment]
DONE

**Comment by kinsyou** [comment]
继续定制已经起作用，但是当定制两本时，第一本的金额出现的是合计金额。
<img width="752" alt="screen shot 2015-12-24 at 09 28 50" src="https://cloud.githubusercontent.com/assets/1054934/11987814/d0095f92-aa20-11e5-96e8-cde3021349cb.png">

**Comment by kinsyou** [comment]
当前本数能否修改？

**Comment by karaokok** [comment]
當前本數不能修改的

**Comment by kinsyou** [comment]
了解，那就合计的bug修正下吧。

**Comment by karaokok** [comment]
那個是合計金額，只是位置不對，我調整一下

**Comment by karaokok** [comment]
我先把合計拿掉，因為目前也無法選擇數量

**Comment by karaokok** [comment]
完成

**Comment by kinsyou** [comment]
仍然显示错误的合计

<img width="554" alt="screen shot 2015-12-25 at 20 08 42" src="https://cloud.githubusercontent.com/assets/1054934/12002741/69747f9a-ab43-11e5-9b85-9a2b2fe293be.png">

**Comment by kinsyou** [comment]
已确认
