### ISSUE TITLE
印刷版中需要条码的生成

### ISSUE THREAD

**Issue by kinsyou** [babyinbook/preview#32]
* 在内页的最后一页和封底中需要嵌入条码
* 每一本书需要生成一个条码，前四位固定为2101，后跟12位数字，共16位。
* 每个订单需要一个订单号，前四位固定为2101，后跟10位数字，共14位，用来查询印厂的订单状态 （详见印厂文档）。

![1 pic](https://cloud.githubusercontent.com/assets/1054934/11928214/afa3b790-a80c-11e5-8bd5-a3efa7514f9d.jpg)
![2 pic](https://cloud.githubusercontent.com/assets/1054934/11928215/b035e17e-a80c-11e5-838a-59317b10ef7e.jpg)
[微印网订单接入文档.docx](https://github.com/babyinbook/preview/files/68318/default.docx)

**Comment by kinsyou** [comment]
12/24

**Comment by karaokok** [comment]
完成

**Comment by kinsyou** [comment]
内页的最后一页也需要bar code

**Comment by karaokok** [comment]
封底有被截掉

**Comment by karaokok** [comment]
調整完成

**Comment by kinsyou** [comment]
已确认
