### ISSUE TITLE
无法生成订单

### ISSUE THREAD

**Issue by kinsyou** [babyinbook/preview#34]
支付后的跳转到之前的测试环境

**Comment by kinsyou** [comment]
支付宝范围正常，生成订单号，但是后台页面中无法看到订单。

**Comment by karaokok** [comment]
done

**Comment by kinsyou** [comment]
后台可以看到订单，但是订单中没有内容。无法生成pdf。显示的本数和日期也有问题。
<img width="436" alt="screen shot 2015-12-24 at 09 38 50" src="https://cloud.githubusercontent.com/assets/1054934/11987893/33847bb4-aa22-11e5-9fe1-c33f1d1ab198.png">
<img width="773" alt="screen shot 2015-12-24 at 09 37 35" src="https://cloud.githubusercontent.com/assets/1054934/11987894/338753f2-aa22-11e5-92c4-e66930204358.png">

**Comment by karaokok** [comment]
完成

**Comment by kinsyou** [comment]
已经确认
