### ISSUE TITLE
增加手机注册的选择

### ISSUE THREAD

**Issue by kinsyou** [babyinbook/preview#38]
包括找回密码等相关功能

**Comment by coolxyz** [comment]
在发送验证码之前需要有图片验证功能，参考如下
https://blog.yunpian.com/?p=50
短信发送API文档如下：
https://www.yunpian.com/api/sms.html
其中apikey为：6dd5ded357d3800bc23b043733cf293d
text为：【宝贝在书里】您的验证码是543678。如非本人操作，请忽略本短信
543678为验证码，可以任意，但其他部分不能修改
当前设置了发送IP白名单，只能通过bib的server发送，测试请在服务器上进行

**Comment by karaokok** [comment]
已完成，但无法测试简讯端

**Comment by kinsyou** [comment]
已确认
