### ISSUE TITLE
有些情况下名字和文章有重叠

### ISSUE THREAD

**Issue by kinsyou** [babyinbook/preview#4]
![5](https://cloud.githubusercontent.com/assets/1054934/11646167/19b702d0-9d96-11e5-905c-aee32dba0eaf.jpg)

**Comment by ClaudiaLee** [comment]
1. 這二個頁面的字距我們會由設計和RD一起合作，先調整。
2. 其它繪本頁面，有名字的位置，先確認為四個中文字大小的空間。我們製作時，就不會產生重疊字的狀況。

**Comment by jane1978** [comment]
请问你说的四个中文字大小，是指的正文的字号大小吗？现在排版是把名字空出来，还是某某某？

**Comment by jane1978** [comment]
现在正文的字号是15号，你们需要名字处理成某某某某四个字，然后都用15号字、正常字间距？是这样吗？之前的某某某是20号字、100号的字间距。

**Comment by ClaudiaLee** [comment]
不要有某某某喔！只要空格，大小_J後回覆。

 From Claudia's iPhone

**Comment by jane1978** [comment]
不要某某某，是指PDF文件不要，还是JPG?没有某某某你们如何定位？

**Comment by TCarol** [comment]
是jpg不要某某某，pdf還是要保留提供給IT校對位置使用。

**Comment by jane1978** [comment]
那就是要做两个源文件，导出两个PDF，一个有某某某，一个没有某某某，没有某某某的PDF再给你导出精度300点的JPG？

**Comment by jane1978** [comment]
现在确定某某某的字号和字间距了吗？

**Comment by TCarol** [comment]
没有某某某的PDF再给你导出精度300点的JPG，這部分可否麻煩直接存成JPG即可，不用再提供沒有某某某給我們PDF，這樣我們這邊會做重複轉檔工作的時間

**Comment by jane1978** [comment]
关于名字的空间
我们的想法是：喵呜体，三个字20号，字间距100；或者，四个字15号，0间距；
你们的想法是：喵呜体，四个字18号，0间距；
我们最终要确定一个。

**Comment by kinsyou** [comment]
具体方案已经确定，记录在 https://github.com/babyinbook/preview/wiki/印刷相关标准
