### ISSUE TITLE
印刷版中没有包含定制的Message

### ISSUE THREAD

**Issue by kinsyou** [babyinbook/preview#51]

**Comment by karaokok** [comment]
已修正

**Comment by kinsyou** [comment]
预览和印刷版的效果不同

**Comment by kinsyou** [comment]
预览的的字体有大有小，pdf的字体都是一样的。请确认。

<img width="297" alt="screen shot 2015-12-29 at 21 31 36" src="https://cloud.githubusercontent.com/assets/1054934/12035091/1780cc1e-ae74-11e5-8f3f-ef7d74e9aca8.png">
<img width="352" alt="screen shot 2015-12-29 at 21 24 32" src="https://cloud.githubusercontent.com/assets/1054934/12035092/1825b9f4-ae74-11e5-90ae-d70a9e6f84e1.png">

**Comment by kinsyou** [comment]
暂时没有问题。
