### ISSUE TITLE
印刷版的封面的尺寸不对

### ISSUE THREAD

**Issue by kinsyou** [babyinbook/preview#53]
当前提供的jpg档的尺寸不对 @jane1978 
转成pdf档时为什么长款都会留白边 @karaokok

https://github.com/babyinbook/preview/wiki/印刷相关标准#印刷文件格式

**Comment by kinsyou** [comment]
封面的尺寸有调整，请使用59.75x22.8 @karaokok

**Comment by karaokok** [comment]
完成

**Comment by kinsyou** [comment]
已确认
