### ISSUE TITLE
印刷业务调整

### ISSUE THREAD

**Issue by kinsyou** [babyinbook/preview#61]
* 当用户支付之后自动异步生成印刷用pdf文件
* 订单详细信息中包含每个货品的cover和content的pdf下载链接
* 后台的订单管理中去除生成印刷文件相关的操作
* 每个订单包含选择框，可通过点按批量发送印厂将所选中的订单发送到印刷厂

**Comment by coolxyz** [comment]
nodejs的实现方法在server的/root/orderManager/placeOrder.js，可以参考一下。

**Comment by kinsyou** [comment]
当前存在的问题整理一下
* 订单号是14位的，书号则必须是这14位编码的后面加上从01到99的2位数，共16位（每个订单最多99本书）
* pdf的URL不应该是preview中的pdf

**Comment by karaokok** [comment]
有了，但因為目前我是先產生後寫入，所以訂單後面兩位數是隨機 01 ~ 99

**Comment by kinsyou** [comment]
当前生成一个两本书的订单，号码如下：
* 订单号：`2101145290665367`
* 书号：`2101145290643101`
* 书号：`2101145290668425`

存在问题
* 订单号：应该是14位而不是16位，比如`21011452906653`
* 书号：应该是订单号后面+两位形成，比如`2101145290665301`，`2101145290665302`

根据以上逻辑书号的生成一定是订单生成的时候（支付完成）根据书本数目顺序为01一直到99。（超过99本时订单生成出错）因此先前生成的目录名关联书号的方法必须修改。

**Comment by kinsyou** [comment]
当前存在几个问题
* 订单号为13位了，应该14位
* 一个订单中的书号会发生重复，服务器中后面那本书覆盖了前订单。详见 2101145309448 的订单。

**Comment by karaokok** [comment]
完全確認了

**Comment by kinsyou** [comment]
暂且关闭。
