### ISSUE TITLE
购物和结算的体验调整

### ISSUE THREAD

**Issue by kinsyou** [babyinbook/preview#63]
* 结算确认进入支付时，用户输入的配送和发票信息应该保存／更新到用户账号内。之后在结算输入页面自动缺省使用该信息。
* 结算输入时发票的是否顺序应该是"否"，“是”，当前相反。

**Comment by kinsyou** [comment]
配送和发票信息应该保存／更新到用户账号这个功能是否实现了呢？

**Comment by karaokok** [comment]
目前作法是，當用戶成功完成一次訂單，會把最後一次的訂單資訊當成缺省值帶入

**Comment by kinsyou** [comment]
确认
