### ISSUE TITLE
定制寄语页的体验调整

### ISSUE THREAD

**Issue by kinsyou** [babyinbook/preview#64]
* 去除金额的显示
* 显示上传照片的缺省显示应该是选择的该角色的缺省扉页中的头像，当前是固定红色小女孩图片。
* 上传照片按钮上需要时“某某某的冒险故事”，当前名字部分为空白
* 增加“送给”输入框，详见 #63

**Comment by karaokok** [comment]
@jane1978

**Comment by karaokok** [comment]
@TCarol  這才是正確的

**Comment by kinsyou** [comment]
已确认
