### ISSUE TITLE
忘记密码的业务没有实现

### ISSUE THREAD

**Issue by kinsyou** [babyinbook/preview#67]

**Comment by kinsyou** [comment]
暂时不用考虑邮件注册的情况。

**Comment by kinsyou** [comment]
新密码没有发送到短信上

**Comment by karaokok** [comment]
有實作，不知道為何沒發送，可能需要協助收收看

**Comment by kinsyou** [comment]
想起来了，所有短信的内容需要有模版才能发，可能该内容没有存在的模版。 @karaokok 请提供短信的内容例子， @coolxyz 请加入模版。

**Comment by karaokok** [comment]
因該不是，因為註冊也沒有模板也是收得到

**Comment by kinsyou** [comment]
注册的话应该是有缺省模版，比较接近的话就会通过，请把所有简讯需要的文字部分告诉我们。 @karaokok

**Comment by karaokok** [comment]
【宝贝在书里】您的新密码是XXXXXX。如非本人操作，请忽略本短信

**Comment by kinsyou** [comment]
模版加入后，已经成功
