### ISSUE TITLE
手机注册账号的流程改进

### ISSUE THREAD

**Issue by kinsyou** [babyinbook/preview#68]
* 缺省改为手机注册
* 手机注册改为两步
 * 第一步为输入手机号和图形验证码
 * 第二步为输入手机认证码和密码
* 手机输入框内写明大陆手机号码，使用时加上 +86
* 当前认证码相关的内容有些写成了验证码，统一为认证码。

**Comment by kinsyou** [comment]
* 界面上隐藏邮件注册模块（当前我们只使用手机注册）
* 可以考虑手机注册的两步仍然放在一个界面上，只需要验证码和认证码的顺序颠倒即可。

**Comment by karaokok** [comment]
加入分隔線

**Comment by kinsyou** [comment]
* 最后submit后提示电话号码错误

<img width="681" alt="screen shot 2016-01-09 at 06 57 20" src="https://cloud.githubusercontent.com/assets/1054934/12211761/5664f1bc-b69e-11e5-85e6-5770b14a46cf.png">

**Comment by karaokok** [comment]
完成

**Comment by kinsyou** [comment]
补充几个细节，请修正后确认
* 认证码一般采用6位
* 验证码发送应该是认证码发送
* 最后注册时不需要校验验证码，只有发送认证码时才需要验证码。
* 手机注册成功后应该自动登录
* 如果是在购买流程中的注册，注册成功后自动登录后直接进入购物车页面。

**Comment by karaokok** [comment]
完成

**Comment by kinsyou** [comment]
已确认
