### ISSUE TITLE
首次登陆后没有显示购物车货物数量

### ISSUE THREAD

**Issue by kinsyou** [babyinbook/preview#72]
* 登录前显示的是0件，登陆后空白
<img width="202" alt="screen shot 2016-01-09 at 07 19 12" src="https://cloud.githubusercontent.com/assets/1054934/12212097/55ce24c8-b6a1-11e5-918d-1f0f2fb48857.png">

**Comment by karaokok** [comment]
完成

**Comment by kinsyou** [comment]
已确认
