### ISSUE TITLE
上传大Size的照片时被拒绝

### ISSUE THREAD

**Issue by kinsyou** [babyinbook/preview#82]

**Comment by karaokok** [comment]
要開多大的 size 呢

**Comment by kinsyou** [comment]
是在哪里设置的呢？（先设置5M吧）

**Comment by karaokok** [comment]
已開

**Comment by kinsyou** [comment]
仍然有如下错误，请在服务器测试
Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)
dropzone.min.js:1 POST http://rc.babyinbook.com/upload.json 413 (Request Entity Too Large)

**Comment by kinsyou** [comment]
@karaokok  你看看这个照片，仍然报错
[IMG_4458.jpg.zip](https://github.com/babyinbook/preview/files/91415/IMG_4458.jpg.zip)

**Comment by karaokok** [comment]
可以了，之前一直在設定 apache，原來是 nginx 誤會了

**Comment by kinsyou** [comment]
已确认
