### ISSUE TITLE
支付宝当场支付失败，后续支付后，订单无法生成。

### ISSUE THREAD

**Issue by kinsyou** [babyinbook/preview#84]
* 支付宝当场支付失败，后续支付后。订单无法生成。
* 尝试再次购买时出现如下信息。

交易已经支付
错误码：TRADE_HAS_SUCCESS

**Comment by karaokok** [comment]
有測試沒有當場支付，而是晚一點支付，還是會回 call 回網站，正常

**Comment by kinsyou** [comment]
问题仍然存在，关键要支付失败后，再选择支付。
这个需要对支付宝的接口做进一步的确认后设计对应方案了。可以考虑后期对应。

**Comment by karaokok** [comment]
建議這樣，我每次購買都產生一組新的序號來對應，就不要用 orderid，這樣就算失敗，也可以再度付款

**Comment by kinsyou** [comment]
当然上述方案是需要的，最先要解决的问题是支付宝付了款但是我们系统没有生成订单。这个明天商量吧。

**Comment by kinsyou** [comment]
已确认
